'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.34209
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DialUpEmulator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1271570_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1271570_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialup_final() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialup_final", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property dialup_snd() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("dialup_snd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Disconnected ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus0() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Connecting ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus1() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Authentication failed ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus10() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid address ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus11() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Credentials required ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus12() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Connected ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus2() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Disconnecting ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus3() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hardware not present ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus4() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hardware disabled ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus5() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hardware malfunction ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus6() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Media disconnected ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus7() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Authenticating ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus8() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Authentication succeeded ähnelt.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus9() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_connection_win95() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_connection_win95", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paypal_donate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paypal_donate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property setting_modem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setting modem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win95dialup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win95dialup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win95dialup_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win95dialup_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
