'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DialUpEmulator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1271570_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1271570_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialup_final() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialup_final", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property dialup_snd() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("dialup_snd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disconnected.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus0() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connecting.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus1() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authentication failed.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus10() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid address.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus11() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credentials required.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus12() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connected.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus2() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disconnecting.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus3() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hardware not present.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus4() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hardware disabled.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus5() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hardware malfunction.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus6() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Media disconnected.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus7() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authenticating.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus8() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authentication succeeded.
        '''</summary>
        Friend ReadOnly Property NetConnectionStatus9() As String
            Get
                Return ResourceManager.GetString("NetConnectionStatus9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_connection_win95() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_connection_win95", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paypal_donate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paypal_donate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property setting_modem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setting modem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win95dialup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win95dialup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win95dialup_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win95dialup_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
